[env]
_.python.venv = { path = "{{config_root}}/.venv", create = true } # required:template
KUBECONFIG = "{{config_root}}/kubeconfig"
SOPS_AGE_KEY_FILE = "{{config_root}}/age.key"
TALOSCONFIG = "{{config_root}}/talos/clusterconfig/talosconfig"

[tasks.deps]
description = "Install Helm dependencies"
run = [
  "helm plugin list | grep -q 'secrets' && helm plugin update secrets || helm plugin install https://github.com/jkroepke/helm-secrets",
  "helm plugin list | grep -q 'diff' && helm plugin update diff || helm plugin install https://github.com/databus23/helm-diff"
]

[tools]
"python" = "3.14.3" # required:template
"uv" = "0.10.0" # required:template
"pipx" = "1.8.0" # required:template
"pipx:makejinja" = "2.8.2" # required:template
"aqua:argoproj/argo-cd" = "3.3.0"
"aqua:budimanjojo/talhelper" = "3.1.5"
"aqua:cilium/cilium-cli" = "0.19.1"
"aqua:cli/cli" = "2.86.0"
"aqua:cloudflare/cloudflared" = "2026.2.0"
"aqua:cue-lang/cue" = "0.15.4" # required:template
"aqua:FiloSottile/age" = "1.3.1"
"aqua:getsops/sops" = "3.11.0"
"aqua:go-task/task" = "3.48.0"
"aqua:helm/helm" = "4.1.1"
"aqua:helmfile/helmfile" = "1.2.3"
"aqua:jqlang/jq" = "1.8.1"
"aqua:kubernetes-sigs/kustomize" = "5.8.0"
"aqua:kubernetes/kubernetes/kubectl" = "1.35.1"
"aqua:mikefarah/yq" = "4.52.4"
"aqua:siderolabs/talos" = "1.12.3"
"aqua:yannh/kubeconform" = "0.7.0"
"aqua:viaduct-ai/kustomize-sops" = "4.4.0"
